### ISSUE TITLE
Missing step - Resource Config

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-mysql#290]
There is no instruction in this document to configure **Resource Config**. The user does not have any clue on what needs to be done here. Or, if there is any need to configure a load balancer.

**Comment by bentarnoff** [comment]
Hey @parth-pandit thanks for this. When filing issues in the future, please be sure to indicate which version of the documentation you're referring to, since we publish multiple versions of the MySQL docs.

@crhino @menicosia What should users know about configuring the **Resource Config** section when installing MySQL for PCF? (It appears the MySQL v1 docs do discuss the **Resource Config** section (https://docs-pcf-staging.cfapps.io/p-mysql/1-10/configuring.html#resource-config), so I'm assuming this inquiry is about MySQL v2. Should MySQL v2 users use the **Resource Config** section to configure a load balancer, for instance?

**Comment by bentarnoff** [comment]
Hey @parth-pandit I had an opportunity to catch up with @menicosia, and he explained that there is no need to configure anything in the "Resource Config" section in the MySQL v2 tile since it's only 1 VM. That's why we don't discuss it in the MySQL 2 docs. 

However, we do discuss the "Resource Config" section in the MySQL v1 docs, since there are more configuration opportunities. For instance, https://docs.pivotal.io/p-mysql/1-10/configuring.html#resource-config. 

I'm closing this issue for now but please feel free to reach out with further concerns or questions. Thanks.
